### PR TITLE
removing the need for hardhat in genSelectors.js: passes test

### PR DESCRIPTION
**Pull request by karmabadger**

### CODE REVIEW

**Comment by Timidan** [comment]
This would only work perfectly if `contractName` == `contractFileName` yes? this means if i have multiple contracts in a contract file, it wouldn't detect it?

**Comment by karmabadger** [comment]
oh that's true but it can be updated to that using the same logic. I can do that later when I get enough time.

**Comment by Timidan** [comment]
yea..that's what `hardhat-ethers` does

**Comment by Timidan** [comment]
> oh that's true but it can be updated to that using the same logic. I can do that later when I get enough time.

hmm..is that possible tho?

**Comment by karmabadger** [comment]
image
seems like the artifacts work by filename.sol/contractname.json.
Should be able to check and find the right contract or take a path directly too

**Comment by Timidan** [comment]
Very sorry for taking long to respond to this...this means a `filename` has to be supplied too...right? at least to the script

**Comment by Timidan** [comment]
Will merge this as it seems to reduce test time by approximately 90%...users will just have to make sure to name their contracts the same name as the `.sol` file....which is absolutely a good practice btw

**Pull request merged**
